//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doctor_s_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentNum { get; set; }
        public string PatientIIN { get; set; }
        public System.DateTime Date { get; set; }
        public string Symptoms { get; set; }
        public string Procedures { get; set; }
        public string Medications { get; set; }
        public int Doctor { get; set; }
    
        public virtual Doctor Doctor1 { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
